In [4]:
import pandas as pd
import numpy as np
from pandas import DataFrame
order=pd.read_excel("SuperstoreSales.xls",0)
order.head(2)

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.54,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.93,0.01,Regular Air,-4.64,2.08,...,Ruben Dartt,Alberta,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21

In [5]:
order.columns=[x.replace(' ','_') for x in order.columns]
order.head(2)

,Row_ID,Order_ID,Order_Date,Order_Priority,Order_Quantity,Sales,Discount,Ship_Mode,Profit,Unit_Price,...,Customer_Name,Province,Region,Customer_Segment,Product_Category,Product_Sub-Category,Product_Name,Product_Container,Product_Base_Margin,Ship_Date
0,1,3,2010-10-13,Low,6,261.54,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.93,0.01,Regular Air,-4.64,2.08,...,Ruben Dartt,Alberta,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21

In [6]:
order.columns=[x.upper() for x in order.columns]
order.head(2)

,ROW_ID,ORDER_ID,ORDER_DATE,ORDER_PRIORITY,ORDER_QUANTITY,SALES,DISCOUNT,SHIP_MODE,PROFIT,UNIT_PRICE,...,CUSTOMER_NAME,PROVINCE,REGION,CUSTOMER_SEGMENT,PRODUCT_CATEGORY,PRODUCT_SUB-CATEGORY,PRODUCT_NAME,PRODUCT_CONTAINER,PRODUCT_BASE_MARGIN,SHIP_DATE
0,1,3,2010-10-13,Low,6,261.54,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,2,6,2012-02-20,Not Specified,2,6.93,0.01,Regular Air,-4.64,2.08,...,Ruben Dartt,Alberta,West,Corporate,Office Supplies,"Scissors, Rulers and Trimmers",Kleencut® Forged Office Shears by Acme United ...,Small Pack,0.55,2012-02-21