In [26]:
import pandas as pd
import numpy as np
from pandas import DataFrame
order=pd.read_excel("SuperstoreSales.xls",0)
order.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Order Priority', 'Order Quantity',
       'Sales', 'Discount', 'Ship Mode', 'Profit', 'Unit Price',
       'Shipping Cost', 'Customer Name', 'Province', 'Region',
       'Customer Segment', 'Product Category', 'Product Sub-Category',
       'Product Name', 'Product Container', 'Product Base Margin',
       'Ship Date'],
      dtype='object')

In [2]:
order.isnull()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8385,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8386,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8387,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8388,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8389,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [62]:
order.columns[order.isnull().sum()>1]

Index(['Product Base Margin'], dtype='object')

In [59]:
order[order.columns[order.isnull().sum()>1]]

      Product Base Margin
0                    0.80
1                    0.55
2                    0.65
3                    0.72
4                    0.60
...                   ...
8385                 0.40
8386                 0.57
8387                 0.40
8388                 0.40
8389                 0.84

[8390 rows x 1 columns]

In [46]:
order[order['Product Base Margin'].isnull()]['Product Base Margin']
# order.isnull().sum()

23     NaN
97     NaN
102    NaN
260    NaN
279    NaN
        ..
7628   NaN
7699   NaN
7769   NaN
7825   NaN
8357   NaN
Name: Product Base Margin, Length: 63, dtype: float64

In [64]:
order[order[order.columns[order.isnull().sum()>1][0]].isnull()][order.columns[order.isnull().sum()>1][0]]

23     NaN
97     NaN
102    NaN
260    NaN
279    NaN
        ..
7628   NaN
7699   NaN
7769   NaN
7825   NaN
8357   NaN
Name: Product Base Margin, Length: 63, dtype: float64

In [1]:
order.dropna(how='any').shape

NameError: name 'order' is not defined

In [33]:
order.dropna(how='all',subset=['Product Base Margin']).shape

(8327, 21)

In [35]:
order.dropna(how='all',subset=order.columns[order.isnull().sum()>1]).shape

(8327, 21)